name: Express.js CI
on:
  push:
    branches: [master]
jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "23"
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
